server:
  port: 8086
  servlet:
    context-path: /community

spring:
  application:
    name: community
  datasource:
    username: root
    password: Tan12345
    url: jdbc:mysql://ali:3306/community
  thymeleaf:
    cache: false
  mail:
    host: smtp.qq.com
    port: 465
    username:
    password:
    properties:
      mail:
        smtp:
          ssl:
            enable: true
  redis:
    host: ali
    database: 3

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.tcbaby.community.pojo
  configuration:
    use-generated-keys: true
    map-underscore-to-camel-case: true

# community
community:
  domain: http://localhost/community
  upload:
    path: D:/Downloads/cache/temp/upload-file/
  sensitive-words-file: sensitive-words.txt
  jwt:
    # 密钥
    secret: yYa9nVFPXB6uFhlhU99Il32O1U5GFTSF
    expire: 30
    cookieName: TOKEN
    # 有效时间 （单位分钟）   30分钟 -- 7天
    min_expire_minutes: 30
    max_expire_minutes: 10080